<?php
/**
 * AJAX TinyMce Plugin
 *
 * @see http://drupal.org/project/ajax
 * @see irc://freenode.net/#drupy
 * @depends Drupal 6
 * @author brendoncrawford
 * @note This file uses a 79 character width limit.
 *
 */

/**
 * hook_init
 *
 * @return Bool
 */
function ajax_tinymce_init() {
  drupal_add_js(drupal_get_path('module', 'ajax_tinymce') .
    '/ajax_tinymce.js', 'theme');
  return TRUE;
}

