<?php
/**
 * AJAX Webform Plugin
 *
 * @see http://drupal.org/project/ajax
 * @see irc://freenode.net/#drupy
 * @depends Drupal 6
 * @author brendoncrawford
 * @note This file uses a 79 character width limit.
 *
 */

/**
 * Get webform types
 *
 * @param $types Assoc
 * @return Bool
 */
function ajax_webform_ajax_types(&$types) {
  $webform_node_types = variable_get('webform_node_types', array('webform'));
  $in = '';
  foreach($webform_node_types as $node_type){
  	$in .= '"'.$node_type.'",';
  }
  $in = substr($in, 0,-1);
  
  $q =
    'SELECT ' .
    '  n.nid, ' .
    '  n.title ' .
    'FROM {node} n ' .
    'WHERE n.type IN ('.$in.')';
  $res = db_query($q);
  while ($row = db_fetch_array($res)) {
    $id = 'webform_client_form_' . (int) $row['nid'];
    $types[$id] = t('Webform: ' . $row['title']);
  }
  return TRUE;
}