<?php
/**
 * AJAX LoginTobbogan Plugin
 *
 * @see http://drupal.org/project/ajax
 * @see irc://freenode.net/#drupy
 * @depends Drupal 6
 * @author brendoncrawford
 * @note This file uses a 79 character width limit.
 *
 */

/**
 * Handles a special case for Login Tobaggan redirection
 *
 * @param $form Assoc
 * @return Bool
 */
function ajax_logintobbogan_ajax_alter(&$form, $form_id) {
  global $logintoboggan_denied;
  if (isset($logintoboggan_denied) && $logintoboggan_denied) {
    $q = zzzz_ajax_pathinfo($form['#action']);
    if (!array_key_exists('destination', $q['query'])) {
      $p = zzzz_ajax_todrupalpath($form['#action']);
      $q['query']['destination'] = $p;
      $form['#action'] = url($p, array(
        'query' => $q['query'],
        'fragment' => $q['fragment'],
        'absolute' => FALSE
      ));
    }
  }
  else {
    return FALSE;
  }
}